/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___DM_MARSHAL_MARSHAL_H__
#define ___DM_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:VOID (marshal.list:25) */
#define _dm_marshal_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* VOID:POINTER (marshal.list:26) */
#define _dm_marshal_VOID__POINTER	g_cclosure_marshal_VOID__POINTER

/* VOID:INT,ENUM,STRING (marshal.list:27) */
extern
void _dm_marshal_VOID__INT_ENUM_STRING (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);

/* VOID:OBJECT (marshal.list:28) */
#define _dm_marshal_VOID__OBJECT	g_cclosure_marshal_VOID__OBJECT


G_END_DECLS

#endif /* ___DM_MARSHAL_MARSHAL_H__ */
