/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaInputStream */

#ifndef _Included_GdaInputStream
#define _Included_GdaInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef GdaInputStream_MAX_SKIP_BUFFER_SIZE
#define GdaInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef GdaInputStream_DEFAULT_BUFFER_SIZE
#define GdaInputStream_DEFAULT_BUFFER_SIZE 8192L
#undef GdaInputStream_MAX_BUFFER_SIZE
#define GdaInputStream_MAX_BUFFER_SIZE 2147483639L
/*
 * Class:     GdaInputStream
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaInputStream_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     GdaInputStream
 * Method:    readByteData
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GdaInputStream_readByteData
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
