/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJMeta */

#ifndef _Included_GdaJMeta
#define _Included_GdaJMeta
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJMeta
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJMeta_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
