/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJColumnInfos */

#ifndef _Included_GdaJColumnInfos
#define _Included_GdaJColumnInfos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJColumnInfos
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJColumnInfos_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
