/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJProvider */

#ifndef _Included_GdaJProvider
#define _Included_GdaJProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJProvider
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJProvider_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
