/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJValue */

#ifndef _Included_GdaJValue
#define _Included_GdaJValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJValue
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJValue_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     GdaJValue
 * Method:    setCString
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCString
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     GdaJValue
 * Method:    setCInt
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCInt
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     GdaJValue
 * Method:    setCChar
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCChar
  (JNIEnv *, jobject, jlong, jint, jbyte);

/*
 * Class:     GdaJValue
 * Method:    setCDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCDouble
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     GdaJValue
 * Method:    setCFloat
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCFloat
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     GdaJValue
 * Method:    setCLong
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCLong
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     GdaJValue
 * Method:    setCShort
 * Signature: (JIS)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCShort
  (JNIEnv *, jobject, jlong, jint, jshort);

/*
 * Class:     GdaJValue
 * Method:    setCBoolean
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCBoolean
  (JNIEnv *, jobject, jlong, jint, jboolean);

/*
 * Class:     GdaJValue
 * Method:    setCDate
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCDate
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     GdaJValue
 * Method:    setCTime
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCTime
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     GdaJValue
 * Method:    setCTimestamp
 * Signature: (JIIIIIII)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCTimestamp
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     GdaJValue
 * Method:    setCBinary
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCBinary
  (JNIEnv *, jobject, jlong, jint, jbyteArray);

/*
 * Class:     GdaJValue
 * Method:    setCBlob
 * Signature: (JIJLGdaJBlobOp;)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCBlob
  (JNIEnv *, jobject, jlong, jint, jlong, jobject);

/*
 * Class:     GdaJValue
 * Method:    setCNumeric
 * Signature: (JILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_GdaJValue_setCNumeric
  (JNIEnv *, jobject, jlong, jint, jstring, jint, jint);

/*
 * Class:     GdaJValue
 * Method:    getCString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GdaJValue_getCString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_GdaJValue_getCInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCChar
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_GdaJValue_getCChar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_GdaJValue_getCDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_GdaJValue_getCFloat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_GdaJValue_getCLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCShort
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_GdaJValue_getCShort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCBoolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_GdaJValue_getCBoolean
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCDate
 * Signature: (J)Ljava/sql/Date;
 */
JNIEXPORT jobject JNICALL Java_GdaJValue_getCDate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCTime
 * Signature: (J)Ljava/sql/Time;
 */
JNIEXPORT jobject JNICALL Java_GdaJValue_getCTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCTimestamp
 * Signature: (J)Ljava/sql/Timestamp;
 */
JNIEXPORT jobject JNICALL Java_GdaJValue_getCTimestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCBinary
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GdaJValue_getCBinary
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCBlob
 * Signature: (J)LGdaInputStream;
 */
JNIEXPORT jobject JNICALL Java_GdaJValue_getCBlob
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GdaJValue
 * Method:    getCNumeric
 * Signature: (J)Ljava/math/BigDecimal;
 */
JNIEXPORT jobject JNICALL Java_GdaJValue_getCNumeric
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
