/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJConnection */

#ifndef _Included_GdaJConnection
#define _Included_GdaJConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJConnection
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJConnection_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
