/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJBlobOp */

#ifndef _Included_GdaJBlobOp
#define _Included_GdaJBlobOp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJBlobOp
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJBlobOp_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
