/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJPStmt */

#ifndef _Included_GdaJPStmt
#define _Included_GdaJPStmt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJPStmt
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJPStmt_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
