/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJResultSetInfos */

#ifndef _Included_GdaJResultSetInfos
#define _Included_GdaJResultSetInfos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJResultSetInfos
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJResultSetInfos_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
