/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GdaJResultSet */

#ifndef _Included_GdaJResultSet
#define _Included_GdaJResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GdaJResultSet
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GdaJResultSet_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
