#define T_ID                              1
#define T_ABORT                           2
#define T_AFTER                           3
#define T_ANALYZE                         4
#define T_ASC                             5
#define T_ATTACH                          6
#define T_BEFORE                          7
#define T_BEGIN                           8
#define T_CASCADE                         9
#define T_CAST                           10
#define T_CONFLICT                       11
#define T_DATABASE                       12
#define T_DEFERRED                       13
#define T_DESC                           14
#define T_DETACH                         15
#define T_EACH                           16
#define T_END                            17
#define T_EXCLUSIVE                      18
#define T_EXPLAIN                        19
#define T_FAIL                           20
#define T_FOR                            21
#define T_IGNORE                         22
#define T_IMMEDIATE                      23
#define T_INITIALLY                      24
#define T_INSTEAD                        25
#define T_LIKE                           26
#define T_MATCH                          27
#define T_PLAN                           28
#define T_QUERY                          29
#define T_KEY                            30
#define T_OF                             31
#define T_OFFSET                         32
#define T_PRAGMA                         33
#define T_RAISE                          34
#define T_REPLACE                        35
#define T_RESTRICT                       36
#define T_ROW                            37
#define T_TEMP                           38
#define T_TRIGGER                        39
#define T_VACUUM                         40
#define T_VIEW                           41
#define T_VIRTUAL                        42
#define T_REINDEX                        43
#define T_RENAME                         44
#define T_CTIME_KW                       45
#define T_IF                             46
#define T_DELIMITER                      47
#define T_COMMIT                         48
#define T_ROLLBACK                       49
#define T_ISOLATION                      50
#define T_LEVEL                          51
#define T_SERIALIZABLE                   52
#define T_READ                           53
#define T_COMMITTED                      54
#define T_UNCOMMITTED                    55
#define T_REPEATABLE                     56
#define T_WRITE                          57
#define T_ONLY                           58
#define T_SAVEPOINT                      59
#define T_RELEASE                        60
#define T_COMMENT                        61
#define T_FORCE                          62
#define T_WAIT                           63
#define T_NOWAIT                         64
#define T_BATCH                          65
#define T_OR                             66
#define T_AND                            67
#define T_NOT                            68
#define T_IS                             69
#define T_NOTLIKE                        70
#define T_IN                             71
#define T_ISNULL                         72
#define T_NOTNULL                        73
#define T_DIFF                           74
#define T_EQ                             75
#define T_BETWEEN                        76
#define T_GT                             77
#define T_LEQ                            78
#define T_LT                             79
#define T_GEQ                            80
#define T_REGEXP                         81
#define T_REGEXP_CI                      82
#define T_NOT_REGEXP                     83
#define T_NOT_REGEXP_CI                  84
#define T_SIMILAR                        85
#define T_ESCAPE                         86
#define T_BITAND                         87
#define T_BITOR                          88
#define T_LSHIFT                         89
#define T_RSHIFT                         90
#define T_PLUS                           91
#define T_MINUS                          92
#define T_STAR                           93
#define T_SLASH                          94
#define T_REM                            95
#define T_CONCAT                         96
#define T_COLLATE                        97
#define T_UMINUS                         98
#define T_UPLUS                          99
#define T_BITNOT                         100
#define T_LP                             101
#define T_RP                             102
#define T_JOIN                           103
#define T_INNER                          104
#define T_NATURAL                        105
#define T_LEFT                           106
#define T_RIGHT                          107
#define T_FULL                           108
#define T_CROSS                          109
#define T_UNION                          110
#define T_EXCEPT                         111
#define T_INTERSECT                      112
#define T_PGCAST                         113
#define T_ILLEGAL                        114
#define T_SQLCOMMENT                     115
#define T_SEMI                           116
#define T_END_OF_FILE                    117
#define T_TRANSACTION                    118
#define T_STRING                         119
#define T_COMMA                          120
#define T_INTEGER                        121
#define T_TO                             122
#define T_INSERT                         123
#define T_INTO                           124
#define T_VALUES                         125
#define T_DELETE                         126
#define T_FROM                           127
#define T_WHERE                          128
#define T_UPDATE                         129
#define T_SET                            130
#define T_ALL                            131
#define T_SELECT                         132
#define T_LIMIT                          133
#define T_ORDER                          134
#define T_BY                             135
#define T_HAVING                         136
#define T_GROUP                          137
#define T_USING                          138
#define T_ON                             139
#define T_OUTER                          140
#define T_DOT                            141
#define T_AS                             142
#define T_DISTINCT                       143
#define T_CASE                           144
#define T_WHEN                           145
#define T_THEN                           146
#define T_ELSE                           147
#define T_NULL                           148
#define T_FLOAT                          149
#define T_UNSPECVAL                      150
#define T_LSBRACKET                      151
#define T_RSBRACKET                      152
#define T_SIMPLEPARAM                    153
#define T_PNAME                          154
#define T_PDESCR                         155
#define T_PTYPE                          156
#define T_PNULLOK                        157
#define T_TEXTUAL                        158
