/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___MARSHAL_MARSHAL_H__
#define ___MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:BOOLEAN,STRING (marshal.list:25) */
extern
void _marshal_VOID__BOOLEAN_STRING (GClosure     *closure,
                                    GValue       *return_value,
                                    guint         n_param_values,
                                    const GValue *param_values,
                                    gpointer      invocation_hint,
                                    gpointer      marshal_data);

/* VOID:POINTER,POINTER,STRING,STRING (marshal.list:26) */
extern
void _marshal_VOID__POINTER_POINTER_STRING_STRING (GClosure     *closure,
                                                   GValue       *return_value,
                                                   guint         n_param_values,
                                                   const GValue *param_values,
                                                   gpointer      invocation_hint,
                                                   gpointer      marshal_data);


G_END_DECLS

#endif /* ___MARSHAL_MARSHAL_H__ */
