/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef ___GDAUI_MARSHAL_MARSHAL_H__
#define ___GDAUI_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:VOID (gdaui-marshal.list:25) */
#define _gdaui_marshal_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* VOID:POINTER (gdaui-marshal.list:26) */
#define _gdaui_marshal_VOID__POINTER	g_cclosure_marshal_VOID__POINTER

/* VOID:OBJECT (gdaui-marshal.list:27) */
#define _gdaui_marshal_VOID__OBJECT	g_cclosure_marshal_VOID__OBJECT

/* VOID:OBJECT,OBJECT (gdaui-marshal.list:28) */
extern
void _gdaui_marshal_VOID__OBJECT_OBJECT (GClosure     *closure,
                                         GValue       *return_value,
                                         guint         n_param_values,
                                         const GValue *param_values,
                                         gpointer      invocation_hint,
                                         gpointer      marshal_data);

/* VOID:OBJECT,ENUM,OBJECT (gdaui-marshal.list:29) */
extern
void _gdaui_marshal_VOID__OBJECT_ENUM_OBJECT (GClosure     *closure,
                                              GValue       *return_value,
                                              guint         n_param_values,
                                              const GValue *param_values,
                                              gpointer      invocation_hint,
                                              gpointer      marshal_data);

/* VOID:OBJECT,UINT (gdaui-marshal.list:30) */
extern
void _gdaui_marshal_VOID__OBJECT_UINT (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:OBJECT,UINT,UINT (gdaui-marshal.list:31) */
extern
void _gdaui_marshal_VOID__OBJECT_UINT_UINT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:OBJECT,BOOLEAN (gdaui-marshal.list:32) */
extern
void _gdaui_marshal_VOID__OBJECT_BOOLEAN (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);

/* VOID:STRING,UINT,UINT (gdaui-marshal.list:33) */
extern
void _gdaui_marshal_VOID__STRING_UINT_UINT (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:ENUM,OBJECT (gdaui-marshal.list:34) */
extern
void _gdaui_marshal_VOID__ENUM_OBJECT (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:UINT,POINTER (gdaui-marshal.list:35) */
#define _gdaui_marshal_VOID__UINT_POINTER	g_cclosure_marshal_VOID__UINT_POINTER

/* VOID:INT,INT (gdaui-marshal.list:36) */
extern
void _gdaui_marshal_VOID__INT_INT (GClosure     *closure,
                                   GValue       *return_value,
                                   guint         n_param_values,
                                   const GValue *param_values,
                                   gpointer      invocation_hint,
                                   gpointer      marshal_data);

/* VOID:INT,BOXED,BOXED (gdaui-marshal.list:37) */
extern
void _gdaui_marshal_VOID__INT_BOXED_BOXED (GClosure     *closure,
                                           GValue       *return_value,
                                           guint         n_param_values,
                                           const GValue *param_values,
                                           gpointer      invocation_hint,
                                           gpointer      marshal_data);

/* VOID:INT,BOOLEAN (gdaui-marshal.list:38) */
extern
void _gdaui_marshal_VOID__INT_BOOLEAN (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:STRING,INT (gdaui-marshal.list:39) */
extern
void _gdaui_marshal_VOID__STRING_INT (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* POINTER:POINTER (gdaui-marshal.list:40) */
extern
void _gdaui_marshal_POINTER__POINTER (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* BOOLEAN:POINTER (gdaui-marshal.list:41) */
extern
void _gdaui_marshal_BOOLEAN__POINTER (GClosure     *closure,
                                      GValue       *return_value,
                                      guint         n_param_values,
                                      const GValue *param_values,
                                      gpointer      invocation_hint,
                                      gpointer      marshal_data);

/* VOID:STRING,ENUM (gdaui-marshal.list:42) */
extern
void _gdaui_marshal_VOID__STRING_ENUM (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:BOOLEAN (gdaui-marshal.list:43) */
#define _gdaui_marshal_VOID__BOOLEAN	g_cclosure_marshal_VOID__BOOLEAN

/* VOID:INT (gdaui-marshal.list:44) */
#define _gdaui_marshal_VOID__INT	g_cclosure_marshal_VOID__INT

/* BOOLEAN:STRING (gdaui-marshal.list:45) */
extern
void _gdaui_marshal_BOOLEAN__STRING (GClosure     *closure,
                                     GValue       *return_value,
                                     guint         n_param_values,
                                     const GValue *param_values,
                                     gpointer      invocation_hint,
                                     gpointer      marshal_data);

/* BOOLEAN:STRING,POINTER (gdaui-marshal.list:46) */
extern
void _gdaui_marshal_BOOLEAN__STRING_POINTER (GClosure     *closure,
                                             GValue       *return_value,
                                             guint         n_param_values,
                                             const GValue *param_values,
                                             gpointer      invocation_hint,
                                             gpointer      marshal_data);


G_END_DECLS

#endif /* ___GDAUI_MARSHAL_MARSHAL_H__ */
