#define D_RAWSTRING                       1
#define D_LOOP                            2
#define D_ENDLOOP                         3
#define D_DECLARE                         4
#define D_CREATE                          5
#define D_BLOB                            6
#define D_ILLEGAL                         7
#define D_SQLCOMMENT                      8
#define D_SEMI                            9
#define D_END_OF_FILE                    10
#define D_SPACE                          11
#define D_STRING                         12
#define D_TEXTUAL                        13
#define D_INTEGER                        14
#define D_FLOAT                          15
#define D_UNSPECVAL                      16
#define D_LSBRACKET                      17
#define D_RSBRACKET                      18
#define D_SIMPLEPARAM                    19
#define D_PNAME                          20
#define D_PDESCR                         21
#define D_PTYPE                          22
#define D_PNULLOK                        23
