#define T_ID                              1
#define T_ABORT                           2
#define T_AFTER                           3
#define T_ANALYZE                         4
#define T_ASC                             5
#define T_ATTACH                          6
#define T_BEFORE                          7
#define T_BEGIN                           8
#define T_CASCADE                         9
#define T_CAST                           10
#define T_CONFLICT                       11
#define T_DATABASE                       12
#define T_DEFERRED                       13
#define T_DESC                           14
#define T_DETACH                         15
#define T_EACH                           16
#define T_END                            17
#define T_EXCLUSIVE                      18
#define T_EXPLAIN                        19
#define T_FAIL                           20
#define T_FOR                            21
#define T_IGNORE                         22
#define T_IMMEDIATE                      23
#define T_INITIALLY                      24
#define T_INSTEAD                        25
#define T_LIKE                           26
#define T_ILIKE                          27
#define T_MATCH                          28
#define T_PLAN                           29
#define T_QUERY                          30
#define T_KEY                            31
#define T_OF                             32
#define T_OFFSET                         33
#define T_PRAGMA                         34
#define T_RAISE                          35
#define T_REPLACE                        36
#define T_RESTRICT                       37
#define T_ROW                            38
#define T_TEMP                           39
#define T_TRIGGER                        40
#define T_VACUUM                         41
#define T_VIEW                           42
#define T_VIRTUAL                        43
#define T_REINDEX                        44
#define T_RENAME                         45
#define T_CTIME_KW                       46
#define T_IF                             47
#define T_DELIMITER                      48
#define T_COMMIT                         49
#define T_ROLLBACK                       50
#define T_ISOLATION                      51
#define T_LEVEL                          52
#define T_SERIALIZABLE                   53
#define T_READ                           54
#define T_COMMITTED                      55
#define T_UNCOMMITTED                    56
#define T_REPEATABLE                     57
#define T_WRITE                          58
#define T_ONLY                           59
#define T_SAVEPOINT                      60
#define T_RELEASE                        61
#define T_COMMENT                        62
#define T_FORCE                          63
#define T_WAIT                           64
#define T_NOWAIT                         65
#define T_BATCH                          66
#define T_TEXTUAL                        67
#define T_STRING                         68
#define T_OR                             69
#define T_AND                            70
#define T_NOT                            71
#define T_IS                             72
#define T_NOTLIKE                        73
#define T_NOTILIKE                       74
#define T_IN                             75
#define T_ISNULL                         76
#define T_NOTNULL                        77
#define T_DIFF                           78
#define T_EQ                             79
#define T_BETWEEN                        80
#define T_GT                             81
#define T_LEQ                            82
#define T_LT                             83
#define T_GEQ                            84
#define T_REGEXP                         85
#define T_REGEXP_CI                      86
#define T_NOT_REGEXP                     87
#define T_NOT_REGEXP_CI                  88
#define T_SIMILAR                        89
#define T_ESCAPE                         90
#define T_BITAND                         91
#define T_BITOR                          92
#define T_LSHIFT                         93
#define T_RSHIFT                         94
#define T_PLUS                           95
#define T_MINUS                          96
#define T_STAR                           97
#define T_SLASH                          98
#define T_REM                            99
#define T_CONCAT                         100
#define T_COLLATE                        101
#define T_UMINUS                         102
#define T_UPLUS                          103
#define T_BITNOT                         104
#define T_LP                             105
#define T_RP                             106
#define T_JOIN                           107
#define T_INNER                          108
#define T_NATURAL                        109
#define T_LEFT                           110
#define T_RIGHT                          111
#define T_FULL                           112
#define T_CROSS                          113
#define T_UNION                          114
#define T_EXCEPT                         115
#define T_INTERSECT                      116
#define T_PGCAST                         117
#define T_ILLEGAL                        118
#define T_SQLCOMMENT                     119
#define T_SEMI                           120
#define T_END_OF_FILE                    121
#define T_TRANSACTION                    122
#define T_COMMA                          123
#define T_INTEGER                        124
#define T_TO                             125
#define T_INSERT                         126
#define T_INTO                           127
#define T_VALUES                         128
#define T_DELETE                         129
#define T_FROM                           130
#define T_WHERE                          131
#define T_UPDATE                         132
#define T_SET                            133
#define T_ALL                            134
#define T_SELECT                         135
#define T_LIMIT                          136
#define T_ORDER                          137
#define T_BY                             138
#define T_HAVING                         139
#define T_GROUP                          140
#define T_USING                          141
#define T_ON                             142
#define T_OUTER                          143
#define T_DOT                            144
#define T_AS                             145
#define T_DISTINCT                       146
#define T_CASE                           147
#define T_WHEN                           148
#define T_THEN                           149
#define T_ELSE                           150
#define T_NULL                           151
#define T_FLOAT                          152
#define T_UNSPECVAL                      153
#define T_LSBRACKET                      154
#define T_RSBRACKET                      155
#define T_SIMPLEPARAM                    156
#define T_PNAME                          157
#define T_PDESCR                         158
#define T_PTYPE                          159
#define T_PNULLOK                        160
